In [2]:
%pip install -q psycopg2-binary sqlalchemy pandas kagglehub
!apt-get -qq update
!apt-get -qq install -y postgresql
!service postgresql start
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

import os
import pandas as pd
from sqlalchemy import create_engine, text
import kagglehub


engine = create_engine(
    'postgresql+psycopg2://postgres:postgres@localhost/postgres', future=True
)

with engine.connect() as conn:
    print(conn.execute(text('SELECT version()')).scalar_one())


dataset_dir = kagglehub.dataset_download('olistbr/brazilian-ecommerce')
print(dataset_dir)


files = {
    'olist_customers_raw': 'olist_customers_dataset.csv',
    'olist_orders_raw': 'olist_orders_dataset.csv',
    'olist_order_items_raw': 'olist_order_items_dataset.csv',
    'olist_products_raw': 'olist_products_dataset.csv',
    'olist_sellers_raw': 'olist_sellers_dataset.csv',
    'olist_order_reviews_raw': 'olist_order_reviews_dataset.csv',
}

for table_name, file_name in files.items():
    path = os.path.join(dataset_dir, file_name)
    df = pd.read_csv(path)
    df.to_sql(table_name, engine, if_exists='replace', index=False, chunksize=10_000)
    print(table_name, df.shape)

ddl = [
    "DROP TABLE IF EXISTS customer_segments CASCADE",
    "DROP TABLE IF EXISTS seller_score CASCADE",
    "DROP TABLE IF EXISTS seller_alerts CASCADE",
    "DROP TABLE IF EXISTS olist_customer_dim CASCADE",
    "DROP TABLE IF EXISTS olist_order_reviews CASCADE",
    "DROP TABLE IF EXISTS olist_order_items CASCADE",
    "DROP TABLE IF EXISTS olist_orders CASCADE",
    "DROP TABLE IF EXISTS olist_customers CASCADE",
    "DROP TABLE IF EXISTS olist_products CASCADE",
    "DROP TABLE IF EXISTS olist_sellers CASCADE",
    """CREATE TABLE olist_customers (
        customer_id TEXT PRIMARY KEY,
        customer_unique_id TEXT NOT NULL,
        customer_zip_code_prefix INTEGER,
        customer_city TEXT,
        customer_state CHAR(2) NOT NULL
    )""",
    "CREATE INDEX idx_olist_customers_unique_id ON olist_customers (customer_unique_id)",
    """CREATE TABLE olist_orders (
        order_id TEXT PRIMARY KEY,
        customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
        order_status TEXT NOT NULL,
        order_purchase_timestamp TIMESTAMP NOT NULL,
        order_approved_at TIMESTAMP,
        order_delivered_carrier_date TIMESTAMP,
        order_delivered_customer_date TIMESTAMP,
        order_estimated_delivery_date TIMESTAMP,
        CHECK (order_status IN (
            'created', 'approved', 'invoiced', 'processing',
            'shipped', 'delivered', 'unavailable', 'canceled'
        ))
    )""",
    """CREATE TABLE olist_products (
        product_id TEXT PRIMARY KEY,
        product_category_name TEXT,
        product_name_length INTEGER CHECK (product_name_length IS NULL OR product_name_length >= 0),
        product_description_length INTEGER CHECK (product_description_length IS NULL OR product_description_length >= 0),
        product_photos_qty INTEGER CHECK (product_photos_qty IS NULL OR product_photos_qty >= 0),
        product_weight_g INTEGER CHECK (product_weight_g IS NULL OR product_weight_g >= 0),
        product_length_cm INTEGER CHECK (product_length_cm IS NULL OR product_length_cm >= 0),
        product_height_cm INTEGER CHECK (product_height_cm IS NULL OR product_height_cm >= 0),
        product_width_cm INTEGER CHECK (product_width_cm IS NULL OR product_width_cm >= 0)
    )""",
    """CREATE TABLE olist_sellers (
        seller_id TEXT PRIMARY KEY,
        seller_zip_code_prefix INTEGER,
        seller_city TEXT,
        seller_state CHAR(2) NOT NULL
    )""",
    """CREATE TABLE olist_order_items (
        order_id TEXT NOT NULL REFERENCES olist_orders(order_id),
        order_item_id INTEGER NOT NULL,
        product_id TEXT REFERENCES olist_products(product_id),
        seller_id TEXT REFERENCES olist_sellers(seller_id),
        shipping_limit_date TIMESTAMP,
        price NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
        freight_value NUMERIC(12, 2) CHECK (freight_value IS NULL OR freight_value >= 0),
        PRIMARY KEY (order_id, order_item_id)
    )""",
    "CREATE INDEX idx_olist_order_items_seller_order ON olist_order_items (seller_id, order_id)",
    """CREATE TABLE olist_order_reviews (
        review_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        review_id TEXT,
        order_id TEXT NOT NULL REFERENCES olist_orders(order_id),
        review_score SMALLINT CHECK (review_score BETWEEN 1 AND 5),
        review_comment_title TEXT,
        review_comment_message TEXT,
        review_creation_date TIMESTAMP,
        review_answer_timestamp TIMESTAMP
    )""",
    "CREATE INDEX idx_olist_order_reviews_order_id ON olist_order_reviews (order_id)",
]

with engine.begin() as conn:
    for statement in ddl:
        conn.exec_driver_sql(statement)

inserts = [
    """INSERT INTO olist_customers
    SELECT customer_id, customer_unique_id,
           customer_zip_code_prefix::INTEGER, customer_city, customer_state::CHAR(2)
    FROM olist_customers_raw""",
    """INSERT INTO olist_orders
    SELECT order_id, customer_id, order_status,
           order_purchase_timestamp::TIMESTAMP, order_approved_at::TIMESTAMP,
           order_delivered_carrier_date::TIMESTAMP,
           order_delivered_customer_date::TIMESTAMP,
           order_estimated_delivery_date::TIMESTAMP
    FROM olist_orders_raw""",
    """INSERT INTO olist_products
    SELECT product_id, product_category_name,
           product_name_lenght::INTEGER, product_description_lenght::INTEGER,
           product_photos_qty::INTEGER, product_weight_g::INTEGER,
           product_length_cm::INTEGER, product_height_cm::INTEGER,
           product_width_cm::INTEGER
    FROM olist_products_raw""",
    """INSERT INTO olist_sellers
    SELECT seller_id, seller_zip_code_prefix::INTEGER, seller_city,
           seller_state::CHAR(2)
    FROM olist_sellers_raw""",
    """INSERT INTO olist_order_items
    SELECT order_id, order_item_id::INTEGER, product_id, seller_id,
           shipping_limit_date::TIMESTAMP, price::NUMERIC(12, 2),
           freight_value::NUMERIC(12, 2)
    FROM olist_order_items_raw""",
    """INSERT INTO olist_order_reviews (
        review_id, order_id, review_score, review_comment_title,
        review_comment_message, review_creation_date, review_answer_timestamp
    )
    SELECT review_id, order_id, review_score::SMALLINT,
           review_comment_title, review_comment_message,
           review_creation_date::TIMESTAMP, review_answer_timestamp::TIMESTAMP
    FROM olist_order_reviews_raw""",
]

with engine.begin() as conn:
    for statement in inserts:
        conn.exec_driver_sql(statement)

counts_sql = """
SELECT 'customers' AS table_name, COUNT(*) AS n_rows FROM olist_customers
UNION ALL SELECT 'orders', COUNT(*) FROM olist_orders
UNION ALL SELECT 'order_items', COUNT(*) FROM olist_order_items
UNION ALL SELECT 'products', COUNT(*) FROM olist_products
UNION ALL SELECT 'sellers', COUNT(*) FROM olist_sellers
UNION ALL SELECT 'reviews', COUNT(*) FROM olist_order_reviews
ORDER BY table_name
"""
with engine.connect() as conn:
    display(pd.read_sql(text(counts_sql), conn))

with engine.begin() as conn:
    conn.exec_driver_sql("DROP TABLE IF EXISTS seller_alerts CASCADE")
    conn.exec_driver_sql("""CREATE TABLE seller_alerts (
        alert_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        seller_id TEXT NOT NULL REFERENCES olist_sellers(seller_id),
        alert_type TEXT NOT NULL CHECK (alert_type IN ('late_delivery', 'low_rating', 'data_quality')),
        severity SMALLINT NOT NULL CHECK (severity BETWEEN 1 AND 5),
        details TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )""")

alert_sql = """
WITH seller_orders AS (
    SELECT DISTINCT oi.seller_id, oi.order_id
    FROM olist_order_items AS oi
), late_sellers AS (
    SELECT so.seller_id, COUNT(DISTINCT o.order_id) AS late_orders
    FROM seller_orders AS so
    JOIN olist_orders AS o ON o.order_id = so.order_id
    WHERE o.order_delivered_customer_date IS NOT NULL
      AND o.order_estimated_delivery_date IS NOT NULL
      AND o.order_delivered_customer_date::DATE > o.order_estimated_delivery_date::DATE
    GROUP BY so.seller_id
    ORDER BY late_orders DESC, so.seller_id
    LIMIT 1
)
INSERT INTO seller_alerts (seller_id, alert_type, severity, details)
SELECT seller_id, 'late_delivery', 4,
       'Seller has ' || late_orders || ' late delivered orders in the loaded dataset'
FROM late_sellers
RETURNING alert_id, seller_id, alert_type, severity, created_at
"""
with engine.begin() as conn:
    alert_rows = conn.execute(text(alert_sql)).mappings().all()
alert_audit_log = pd.DataFrame(alert_rows)
display(alert_audit_log)

with engine.begin() as conn:
    conn.exec_driver_sql("DROP TABLE IF EXISTS seller_score CASCADE")
    conn.exec_driver_sql("""CREATE TABLE seller_score (
        seller_id TEXT PRIMARY KEY REFERENCES olist_sellers(seller_id),
        avg_rating NUMERIC(3, 2),
        n_reviews INTEGER NOT NULL DEFAULT 0 CHECK (n_reviews >= 0),
        tier TEXT CHECK (tier IN ('gold', 'silver', 'bronze')),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )""")

seller_score_sql = """
WITH seller_orders AS (
    SELECT DISTINCT oi.seller_id, oi.order_id
    FROM olist_order_items AS oi
), review_per_order AS (
    SELECT rv.order_id, AVG(rv.review_score)::NUMERIC(3, 2) AS order_review_score
    FROM olist_order_reviews AS rv
    WHERE rv.review_score IS NOT NULL
    GROUP BY rv.order_id
), seller_rating AS (
    SELECT so.seller_id,
           AVG(rpo.order_review_score)::NUMERIC(3, 2) AS avg_rating,
           COUNT(rpo.order_id) AS n_reviews
    FROM seller_orders AS so
    LEFT JOIN review_per_order AS rpo ON rpo.order_id = so.order_id
    GROUP BY so.seller_id
)
INSERT INTO seller_score (seller_id, avg_rating, n_reviews, tier)
SELECT seller_id, avg_rating, n_reviews,
       CASE
           WHEN avg_rating IS NULL THEN NULL
           WHEN avg_rating >= 4.5 THEN 'gold'
           WHEN avg_rating >= 3.5 THEN 'silver'
           ELSE 'bronze'
       END AS tier
FROM seller_rating
ON CONFLICT (seller_id) DO UPDATE SET
    avg_rating = EXCLUDED.avg_rating,
    n_reviews = EXCLUDED.n_reviews,
    tier = EXCLUDED.tier,
    updated_at = NOW()
RETURNING seller_id, avg_rating, n_reviews, tier, updated_at
"""
with engine.begin() as conn:
    score_rows = conn.execute(text(seller_score_sql)).mappings().all()
seller_score_result = pd.DataFrame(score_rows)
display(seller_score_result.head(10))
print(f"Upserted {len(seller_score_result):,} seller scores; showing first 10 rows.")

with engine.begin() as conn:
    conn.exec_driver_sql(
        "ALTER TABLE olist_orders ADD COLUMN IF NOT EXISTS is_late BOOLEAN NOT NULL DEFAULT FALSE"
    )
    update_result = conn.execute(text("""
        WITH delivery_flags AS (
            SELECT order_id,
                   (order_delivered_customer_date IS NOT NULL
                    AND order_estimated_delivery_date IS NOT NULL
                    AND order_delivered_customer_date::DATE > order_estimated_delivery_date::DATE) AS is_late_calc
            FROM olist_orders
        )
        UPDATE olist_orders AS o
        SET is_late = f.is_late_calc
        FROM delivery_flags AS f
        WHERE f.order_id = o.order_id
        RETURNING o.order_id, o.customer_id, o.is_late
    """))
    updated_count = update_result.rowcount
    update_sample = update_result.fetchmany(10)
print(f"Updated {updated_count:,} orders; first 10 returned rows:")
display(pd.DataFrame(update_sample, columns=['order_id', 'customer_id', 'is_late']))

delete_sql = """
DELETE FROM seller_alerts
WHERE created_at < NOW() - INTERVAL '30 days'
RETURNING alert_id, seller_id, alert_type, created_at
"""
with engine.begin() as conn:
    deleted_rows = conn.execute(text(delete_sql)).mappings().all()
deleted_alerts = pd.DataFrame(deleted_rows)
display(deleted_alerts)

with engine.begin() as conn:
    conn.exec_driver_sql("DROP TABLE IF EXISTS customer_segments CASCADE")
    conn.exec_driver_sql("DROP TABLE IF EXISTS olist_customer_dim CASCADE")
    conn.exec_driver_sql("""CREATE TABLE olist_customer_dim (
        customer_unique_id TEXT PRIMARY KEY,
        latest_customer_id TEXT REFERENCES olist_customers(customer_id),
        customer_state CHAR(2),
        customer_city TEXT
    )""")
    conn.exec_driver_sql("""INSERT INTO olist_customer_dim (
        customer_unique_id, latest_customer_id, customer_state, customer_city
    )
    SELECT DISTINCT ON (c.customer_unique_id)
        c.customer_unique_id,
        c.customer_id AS latest_customer_id,
        c.customer_state,
        c.customer_city
    FROM olist_customers AS c
    LEFT JOIN olist_orders AS o ON o.customer_id = c.customer_id
    ORDER BY c.customer_unique_id,
             o.order_purchase_timestamp DESC NULLS LAST,
             c.customer_id""")
    dim_count = conn.exec_driver_sql("SELECT COUNT(*) FROM olist_customer_dim").scalar_one()
print(f"Customer dimension rows: {dim_count:,}")

with engine.begin() as conn:
    conn.exec_driver_sql("""CREATE TABLE customer_segments (
        segment_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        customer_unique_id TEXT NOT NULL,
        segment_name TEXT NOT NULL
            CHECK (segment_name IN ('VIP', 'regular', 'new', 'inactive')),
        rfm_score SMALLINT NOT NULL CHECK (rfm_score BETWEEN 1 AND 5),
        recency_days INTEGER CHECK (recency_days IS NULL OR recency_days >= 0),
        monetary_value NUMERIC(12, 2) NOT NULL DEFAULT 0
            CHECK (monetary_value >= 0),
        n_orders INTEGER NOT NULL DEFAULT 0 CHECK (n_orders >= 0),
        assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        UNIQUE (customer_unique_id)
    )""")
    conn.exec_driver_sql("""ALTER TABLE customer_segments
        ADD CONSTRAINT fk_customer_segments_customer_unique
        FOREIGN KEY (customer_unique_id)
        REFERENCES olist_customer_dim(customer_unique_id)
        ON DELETE CASCADE""")

segments_sql = """
WITH reference_date AS (
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
), order_totals AS (
    SELECT o.order_id,
           o.customer_id,
           o.order_purchase_timestamp::DATE AS order_date,
           COALESCE(SUM(oi.price + oi.freight_value), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi ON oi.order_id = o.order_id
    GROUP BY o.order_id, o.customer_id, o.order_purchase_timestamp
), customer_stats AS (
    SELECT c.customer_unique_id,
           COUNT(DISTINCT ot.order_id) AS n_orders,
           COALESCE(SUM(ot.order_total), 0)::NUMERIC(12, 2) AS monetary_value,
           MAX(ot.order_date) AS last_order_date
    FROM olist_customer_dim AS cd
    JOIN olist_customers AS c ON c.customer_unique_id = cd.customer_unique_id
    LEFT JOIN order_totals AS ot ON ot.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
), segmented AS (
    SELECT cs.customer_unique_id,
           cs.n_orders,
           cs.monetary_value,
           CASE WHEN cs.last_order_date IS NULL THEN NULL
                ELSE (rd.as_of_date - cs.last_order_date)::INTEGER
           END AS recency_days,
           CASE
               WHEN cs.monetary_value >= 1000 THEN 'VIP'
               WHEN cs.last_order_date IS NOT NULL
                    AND (rd.as_of_date - cs.last_order_date)::INTEGER <= 90
                    AND cs.n_orders = 1 THEN 'new'
               WHEN cs.n_orders >= 2 OR cs.monetary_value >= 100 THEN 'regular'
               ELSE 'inactive'
           END AS segment_name,
           CASE
               WHEN cs.monetary_value >= 1000 THEN 5
               WHEN cs.monetary_value >= 500 THEN 4
               WHEN cs.n_orders >= 2 THEN 3
               WHEN cs.n_orders = 1 THEN 2
               ELSE 1
           END::SMALLINT AS rfm_score
    FROM customer_stats AS cs
    CROSS JOIN reference_date AS rd
)
INSERT INTO customer_segments (
    customer_unique_id, segment_name, rfm_score,
    recency_days, monetary_value, n_orders
)
SELECT customer_unique_id, segment_name, rfm_score,
       recency_days, monetary_value, n_orders
FROM segmented
ON CONFLICT (customer_unique_id) DO UPDATE SET
    segment_name = EXCLUDED.segment_name,
    rfm_score = EXCLUDED.rfm_score,
    recency_days = EXCLUDED.recency_days,
    monetary_value = EXCLUDED.monetary_value,
    n_orders = EXCLUDED.n_orders,
    assigned_at = NOW()
RETURNING customer_unique_id, segment_name, rfm_score,
          recency_days, monetary_value, n_orders
"""
with engine.begin() as conn:
    segment_result = conn.execute(text(segments_sql))
    segments_upserted = segment_result.rowcount
    segments_sample = segment_result.fetchmany(10)
print(f"Upserted {segments_upserted:,} customer segments; first 10 rows:")
display(pd.DataFrame(segments_sample, columns=[
    'customer_unique_id', 'segment_name', 'rfm_score',
    'recency_days', 'monetary_value', 'n_orders'
]))

constraints_sql = """
SELECT conname, contype, pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE conrelid = 'customer_segments'::regclass
ORDER BY conname
"""
with engine.connect() as conn:
    display(pd.read_sql(text(constraints_sql), conn))

top_categories = """
SELECT p.product_category_name,
       s.seller_state,
       COUNT(DISTINCT oi.order_id) AS n_orders,
       SUM(oi.price + oi.freight_value)::NUMERIC(12, 2) AS revenue
FROM olist_order_items AS oi
JOIN olist_orders AS o ON o.order_id = oi.order_id
JOIN olist_products AS p ON p.product_id = oi.product_id
JOIN olist_sellers AS s ON s.seller_id = oi.seller_id
WHERE o.order_status = 'delivered'
GROUP BY p.product_category_name, s.seller_state
ORDER BY revenue DESC NULLS LAST
LIMIT 10
"""
with engine.connect() as conn:
    result_top_categories = pd.read_sql(text(top_categories), conn)
display(result_top_categories)
if not result_top_categories.empty:
    top = result_top_categories.iloc[0]
    category = top['product_category_name'] if pd.notna(top['product_category_name']) else '(без категорії)'
    print(f"Interpretation: Among the sample of delivered orders, the category {category} with the seller located in {top['seller_state']} generated the highest revenue—{top['revenue']:,.2f}—from {int(top['n_orders'])} orders.")
else:
    print("Interpretation: the query did not return delivered orders with the corresponding product items and sellers.")

without_multiplication = """
WITH order_totals AS (
    SELECT o.order_id,
           c.customer_unique_id,
           SUM(oi.price + oi.freight_value)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    JOIN olist_customers AS c ON c.customer_id = o.customer_id
    LEFT JOIN olist_order_items AS oi ON oi.order_id = o.order_id
    GROUP BY o.order_id, c.customer_unique_id
), review_per_order AS (
    SELECT rv.order_id,
           AVG(rv.review_score)::NUMERIC(3, 2) AS order_review_score
    FROM olist_order_reviews AS rv
    WHERE rv.review_score IS NOT NULL
    GROUP BY rv.order_id
), customer_stats AS (
    SELECT ot.customer_unique_id,
           COUNT(DISTINCT ot.order_id) AS n_orders,
           COALESCE(SUM(ot.order_total), 0)::NUMERIC(12, 2) AS total_spend,
           AVG(rpo.order_review_score)::NUMERIC(3, 2) AS avg_review_score
    FROM order_totals AS ot
    LEFT JOIN review_per_order AS rpo ON rpo.order_id = ot.order_id
    GROUP BY ot.customer_unique_id
)
SELECT cd.customer_unique_id,
       cd.customer_state,
       COALESCE(cs.n_orders, 0) AS n_orders,
       COALESCE(cs.total_spend, 0)::NUMERIC(12, 2) AS total_spend,
       COALESCE(cs.avg_review_score, 0)::NUMERIC(3, 2) AS avg_review_score
FROM olist_customer_dim AS cd
LEFT JOIN customer_stats AS cs ON cs.customer_unique_id = cd.customer_unique_id
ORDER BY total_spend DESC NULLS LAST
LIMIT 20
"""
with engine.connect() as conn:
    result_without_multiplication = pd.read_sql(text(without_multiplication), conn)
display(result_without_multiplication)
if not result_without_multiplication.empty:
    top = result_without_multiplication.iloc[0]
    print(f"Interpretation: Among the customers shown, the highest expenditure is by {top['customer_unique_id']} ({top['customer_state']}): {top['total_spend']:,.2f} across {int(top['n_orders'])} orders; the average order review score is {top['avg_review_score']:.2f}.")
print("Note: `avg_review_score = 0` following `COALESCE` indicates the absence of any non-zero ratings, rather than an actual rating of 0. `review_per_order` prevents a single review from being counted multiple times due to multiple `order_items`.")

states_are_present = """
WITH customer_states AS (
    SELECT customer_state AS state, COUNT(*) AS n_customers
    FROM olist_customers
    GROUP BY customer_state
), seller_states AS (
    SELECT seller_state AS state, COUNT(*) AS n_sellers
    FROM olist_sellers
    GROUP BY seller_state
)
SELECT COALESCE(c.state, s.state) AS state,
       c.n_customers,
       s.n_sellers,
       CASE
           WHEN c.state IS NOT NULL AND s.state IS NOT NULL THEN 'both'
           WHEN c.state IS NOT NULL THEN 'customers_only'
           ELSE 'sellers_only'
       END AS state_presence
FROM customer_states AS c
FULL OUTER JOIN seller_states AS s ON s.state = c.state
ORDER BY state
"""
with engine.connect() as conn:
    result_states_are_present = pd.read_sql(text(states_are_present), conn)
display(result_states_are_present)
if not result_states_are_present.empty:
    presence = result_states_are_present['state_presence'].value_counts().to_dict()
    print(f"Interpretation: based on the actual results, the states are distributed as follows: {presence.get('both', 0)} present in both sets, {presence.get('customers_only', 0)} only among customers, {presence.get('sellers_only', 0)} only among sellers.")
else:
    print("Interpretation: neither table contains states for comparison.")

pairs_of_sellers = """
SELECT s1.seller_id AS seller_a,
       s2.seller_id AS seller_b,
       s1.seller_state,
       s1.seller_city AS city_a,
       s2.seller_city AS city_b
FROM olist_sellers AS s1
JOIN olist_sellers AS s2
  ON s1.seller_state = s2.seller_state
 AND s1.seller_id < s2.seller_id
 AND s1.seller_city IS DISTINCT FROM s2.seller_city
ORDER BY s1.seller_state, seller_a, seller_b
LIMIT 20
"""
with engine.connect() as conn:
    result_pairs_of_sellers = pd.read_sql(text(pairs_of_sellers), conn)
display(result_pairs_of_sellers)
if not result_pairs_of_sellers.empty:
    row = result_pairs_of_sellers.iloc[0]
    print(f"Interpretation: the query found at least {len(result_pairs_of_sellers)} pair(s) on the first page of results; for example, {row['seller_a']} ({row['city_a']}) and {row['seller_b']} ({row['city_b']}) operate in the state of {row['seller_state']}, but list different cities.")
else:
    print("Interpretation: No pairs of sellers from the same state with different city values ​​were found.")
print("These are just the first 20 pairs. `IS DISTINCT FROM` also considers `NULL` to be distinct from a non-empty city, so rows with a missing city should be checked separately.")

without_response = """
SELECT o.order_id,
       o.customer_id,
       o.order_status,
       o.order_purchase_timestamp,
       COUNT(*) OVER() AS total_without_review
FROM olist_orders AS o
LEFT JOIN olist_order_reviews AS rv ON rv.order_id = o.order_id
WHERE rv.review_row_id IS NULL
ORDER BY o.order_purchase_timestamp
LIMIT 20
"""
with engine.connect() as conn:
    result_without_response = pd.read_sql(text(without_response), conn)
display(result_without_response)
if not result_without_response.empty:
    total = int(result_without_response['total_without_review'].iloc[0])
    print(f"Interpretation: there are {total:,} orders with no reviews; the first {len(result_without_response)}, ordered by creation time, are shown above.")
else:
    print("Interpretation: each order has at least one review record.")

RPPC = """
SELECT p.product_category_name,
       COUNT(DISTINCT oi.order_id) AS n_orders,
       SUM(oi.price)::NUMERIC(12, 2) AS gross_revenue,
       SUM(oi.freight_value)::NUMERIC(12, 2) AS freight,
       AVG(oi.price)::NUMERIC(8, 2) AS avg_item_price
FROM olist_order_items AS oi
JOIN olist_products AS p ON p.product_id = oi.product_id
GROUP BY p.product_category_name
HAVING SUM(oi.price) > 10000
ORDER BY gross_revenue DESC NULLS LAST
"""
with engine.connect() as conn:
    result_RPPC = pd.read_sql(text(RPPC), conn)
display(result_RPPC)
if not result_RPPC.empty:
    top = result_RPPC.iloc[0]
    category = top['product_category_name'] if pd.notna(top['product_category_name']) else '(Uncategorized)'
    print(f"Interpretation: Among the categories that passed the HAVING threshold, the highest gross revenue is in the category {category}: {top['gross_revenue']:,.2f}; {int(top['n_orders'])} orders, with an average item price of {top['avg_item_price']:,.2f}.")
else:
    print("Interpretation: No category exceeded a gross revenue of 10,000 based on product prices.")

number_of_orders = """
WITH order_totals AS (
    SELECT o.order_id,
           c.customer_state,
           SUM(oi.price + oi.freight_value)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    JOIN olist_customers AS c ON c.customer_id = o.customer_id
    JOIN olist_order_items AS oi ON oi.order_id = o.order_id
    GROUP BY o.order_id, c.customer_state
)
SELECT customer_state,
       COUNT(*) AS n_orders,
       SUM(order_total)::NUMERIC(12, 2) AS gmv,
       (SUM(order_total) / NULLIF(COUNT(*), 0))::NUMERIC(8, 2) AS aov
FROM order_totals
GROUP BY customer_state
HAVING COUNT(*) >= 100
ORDER BY aov DESC NULLS LAST
"""
with engine.connect() as conn:
    result_number_of_orders = pd.read_sql(text(number_of_orders), conn)
display(result_number_of_orders)
if not result_number_of_orders.empty:
    top = result_number_of_orders.iloc[0]
    print(f"Interpretation: Among states with at least 100 orders, the highest AOV is in {top['customer_state']}: {top['aov']:,.2f} per order ({int(top['n_orders'])} orders, GMV {top['gmv']:,.2f}).")
else:
    print("Interpretation: No state has reached the threshold of 100 orders containing line items.")

genuine_buyer = """
SELECT c.customer_unique_id,
       COUNT(DISTINCT o.order_id) AS n_orders,
       SUM(oi.price)::NUMERIC(12, 2) AS total_spend,
       STRING_AGG(
           DISTINCT COALESCE(p.product_category_name, '(unknown)'),
           ', ' ORDER BY COALESCE(p.product_category_name, '(unknown)')
       ) AS categories
FROM olist_customers AS c
JOIN olist_orders AS o ON o.customer_id = c.customer_id
JOIN olist_order_items AS oi ON oi.order_id = o.order_id
LEFT JOIN olist_products AS p ON p.product_id = oi.product_id
GROUP BY c.customer_unique_id
HAVING COUNT(DISTINCT o.order_id) >= 1
ORDER BY total_spend DESC NULLS LAST
LIMIT 20
"""
with engine.connect() as conn:
    result_genuine_buyer = pd.read_sql(text(genuine_buyer), conn)
display(result_genuine_buyer)
if not result_genuine_buyer.empty:
    top = result_genuine_buyer.iloc[0]
    print(f"ІInterpretation: Among the customers shown, {top['customer_unique_id']} has the highest spending: {top['total_spend']:,.2f} across {int(top['n_orders'])} orders. Categories involved: {top['categories']}.")
else:
    print("Interpretation: No customers with orders and product line items found.")

state_codes = """
SELECT customer_state AS state, 'customer' AS role
FROM olist_customers
UNION
SELECT seller_state AS state, 'seller' AS role
FROM olist_sellers
ORDER BY state, role
"""
with engine.connect() as conn:
    result_state_codes = pd.read_sql(text(state_codes), conn)
display(result_state_codes)
if not result_state_codes.empty:
    state_count = result_state_codes['state'].nunique()
    both_roles = (result_state_codes.groupby('state')['role'].nunique() == 2).sum()
    print(f"Interpretation: There are {state_count} unique state codes in the datasets; {both_roles} of these are represented among both clients and sellers. UNION retained the unique state-role pairs.")
else:
    print("Interpretation: State codes not found in client and seller tables.")

clients_and_sellers = """
WITH ranked_orders AS (
    SELECT c.customer_unique_id,
           o.customer_id,
           o.order_id,
           o.order_purchase_timestamp,
           ROW_NUMBER() OVER (
               PARTITION BY c.customer_unique_id
               ORDER BY o.order_purchase_timestamp DESC, o.order_id DESC
           ) AS rn
    FROM olist_orders AS o
    JOIN olist_customers AS c ON c.customer_id = o.customer_id
)
SELECT customer_unique_id, customer_id, order_id, order_purchase_timestamp
FROM ranked_orders
WHERE rn = 1
ORDER BY customer_unique_id
LIMIT 20
"""
with engine.connect() as conn:
    result_clients_and_sellers = pd.read_sql(text(clients_and_sellers), conn)
display(result_clients_and_sellers)
print(f"Interpretation: {len(result_clients_and_sellers)} customers are shown, along with one most recent order for each of the first 20 customer_unique_id values.")

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
[ OK ]
ALTER ROLE
PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit
Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
/kaggle/input/brazilian-ecommerce
olist_customers_raw (99441, 5)
olist_orders_raw (99441, 8)
olist_order_items_raw (112650, 7)
olist_products_raw (32951, 9)
olist_sellers_raw (3095, 4)
olist_order_reviews_raw (99224, 7)

    table_name  n_rows
0    customers   99441
1  order_items  112650
2       orders   99441
3     products   32951
4      reviews   99224
5      sellers    3095

,alert_id,alert_type,created_at,seller_id,severity
0,1,late_delivery,2026-10-19 17:56:37.315015+00:00,4a3ca9315b744ce9f8e9374361493884,4

,avg_rating,n_reviews,seller_id,tier,updated_at
0,5.00,1,a61cc04793308395a840807104365121,gold,2026-10-19 17:56:37.529902+00:00
1,3.67,3,6d2f2e3b539480db1e0842b3a4e32e6e,silver,2026-10-19 17:56:37.529902+00:00
2,3.20,5,c53bcd3be457a342a97e39e5a9f0be22,bronze,2026-10-19 17:56:37.529902+00:00
3,1.00,1,9591fc341b1bfb7ef561e2968ec6e011,bronze,2026-10-19 17:56:37.529902+00:00
4,4.78,9,f9ec7093df3a7b346b7bcf7864069ca3,gold,2026-10-19 17:56:37.529902+00:00
5,4.60,5,fc38b5dceee1a730fad8853453437fbd,gold,2026-10-19 17:56:37.529902+00:00
6,4.60,5,5def4c3732941a971cba8fdee992ede1,gold,2026-10-19 17:56:37.529902+00:00
7,3.88,43,b39d7fe263ef469605dbb32608aee0af,silver,2026-10-19 17:56:37.529902+00:00
8,4.00,9,ea65d8b58316a6f2362f2a9e4b3e86ad,silver,2026-10-19 17:56:37.529902+00:00
9,4.00,1,a45765f8afb1e594b22bf9e974b46765,silver,2026-10-19 17:56:37.529902+00:00

Upserted 3,095 seller scores; showing first 10 rows.
Updated 99,441 orders; first 10 returned rows:

                           order_id                       customer_id  is_late
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d    False
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef    False
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089    False
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82    False
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c    False
5  a4591c265e18cb1dcee52889e2d8acc3  503740e9ca751ccdda7ba28e9ab8f608    False
6  136cce7faa42fdb2cefd53fdc79a6098  ed0271e0b7da060a393796590e7b737a    False
7  6514b8ad8028c9f2cc2374ded245783f  9bdf08b4b3b52b5526ff42d37d47f222    False
8  76c6e866289321a7c93b82b54852dc33  f54a9f0e6b351c431402b8461ea51999    False
9  e69bfb5eb88e0ed6a785585b27e16dbf  31ad1d1b63eb9962463f764d4e6e0c9d    False

Empty DataFrame
Columns: []
Index: []

Customer dimension rows: 96,096
Upserted 96,096 customer segments; first 10 rows:

,customer_unique_id,segment_name,rfm_score,recency_days,monetary_value,n_orders
0,0000366f3b9a7992bf8c76cfdf3221e2,regular,2,161,141.90,1
1,0000b849f77a49e4a4ce2b2a4ca5be3f,inactive,2,164,27.19,1
2,0000f46a3911fa3c0805444483337064,inactive,2,587,86.22,1
3,0000f6ccb0745a6a4b88665a16c9f078,inactive,2,371,43.62,1
4,0004aac84e0df4da2b147fca70cf8255,regular,2,338,196.89,1
5,0004bd2a26a76fe21f786e4fbd80607f,regular,2,196,166.98,1
6,00050ab1314c0e55a6ca13cf7181fecf,inactive,2,181,35.38,1
7,00053a61a98854899e70ed204dd4bafe,regular,2,232,419.18,1
8,0005e1862207bf6ccc02e4228effd9a0,regular,2,593,150.12,1
9,0005ef4cd20d2893f0d9fbd94d3c0d97,regular,2,220,129.76,1

,conname,contype,definition
0,customer_segments_customer_unique_id_key,u,UNIQUE (customer_unique_id)
1,customer_segments_monetary_value_check,c,CHECK ((monetary_value >= (0)::numeric))
2,customer_segments_n_orders_check,c,CHECK ((n_orders >= 0))
3,customer_segments_pkey,p,PRIMARY KEY (segment_id)
4,customer_segments_recency_days_check,c,CHECK (((recency_days IS NULL) OR (recency_day...
5,customer_segments_rfm_score_check,c,CHECK (((rfm_score >= 1) AND (rfm_score <= 5)))
6,customer_segments_segment_name_check,c,"CHECK ((segment_name = ANY (ARRAY['VIP'::text,..."
7,fk_customer_segments_customer_unique,f,FOREIGN KEY (customer_unique_id) REFERENCES ol...

    product_category_name seller_state  n_orders     revenue
0         cama_mesa_banho           SP      8214  1070048.14
1      relogios_presentes           SP      4494  1016168.80
2            beleza_saude           SP      5684   790967.66
3           esporte_lazer           SP      4772   680165.54
4        moveis_decoracao           SP      4597   605650.63
5              cool_stuff           SP      2621   484196.53
6   utilidades_domesticas           SP      4021   471810.66
7              automotivo           SP      3018   438833.22
8  informatica_acessorios           SP      2783   388506.42
9                   bebes           SP      1981   339129.74

Interpretation: Among the sample of delivered orders, the category cama_mesa_banho with the seller located in SP generated the highest revenue—1,070,048.14—from 8214 orders.

,customer_unique_id,customer_state,n_orders,total_spend,avg_review_score
0,0a0a92112bd4c708ca5fde585afaa872,RJ,1,13664.08,1.0
1,da122df9eeddfedc1dc1f5349a1a690c,RJ,2,7571.63,5.0
2,763c8b1c9c68a0229c42c9fc6f662b93,ES,1,7274.88,1.0
3,dc4802a71eae9be1dd28f5d788ceb526,MS,1,6929.31,5.0
4,459bef486812aa25204be022145caa62,ES,1,6922.21,0.0
5,ff4159b92c40ebe40454e3e6a7c35ed6,SP,1,6726.66,5.0
6,4007669dec559734d6f53e029e360987,MG,1,6081.54,1.0
7,5d0a2980b292d049061542014e8960bf,GO,1,4809.44,1.0
8,eebb5dda148d3893cdaf5b5ca3040ccb,SP,1,4764.34,4.0
9,48e1ac109decbb87765a3eade6854098,PB,1,4681.78,5.0
10,c8460e4251689ba205045f3ea17884a1,RS,4,4655.88,4.0
11,edde2314c6c30e864a128ac95d6b2112,SP,1,4513.32,5.0
12,a229eba70ec1c2abef51f04987deb7a5,RJ,1,4445.50,5.0
13,edf81e1f3070b9dac83ec83dacdbb9bc,DF,1,4194.76,2.0
14,fa562ef24d41361e476e748681810e1e,MG,1,4175.26,5.0
15,ca27f3dac28fb1063faddd424c9d95fa,MG,1,4163.51,4.0
16,055ec572ac7f3c7bdd04a183830ebe59,SP,2,4053.08,1.0
17,5e713be0853d8986528d7869a0811d2b,PA,1,4042.74,5.0
18,58483a1c055dfb600f57c5b867174542,SP,1,4034.44,5.0
19,011875f0176909c5cf0b14a9138bb691,SP,1,4016.91,5.0

Interpretation: Among the customers shown, the highest expenditure is by 0a0a92112bd4c708ca5fde585afaa872 (RJ): 13,664.08 across 1 orders; the average order review score is 1.00.
Note: `avg_review_score = 0` following `COALESCE` indicates the absence of any non-zero ratings, rather than an actual rating of 0. `review_per_order` prevents a single review from being counted multiple times due to multiple `order_items`.

   state  n_customers  n_sellers  state_presence
0     AC           81        1.0            both
1     AL          413        NaN  customers_only
2     AM          148        1.0            both
3     AP           68        NaN  customers_only
4     BA         3380       19.0            both
5     CE         1336       13.0            both
6     DF         2140       30.0            both
7     ES         2033       23.0            both
8     GO         2020       40.0            both
9     MA          747        1.0            both
10    MG        11635      244.0            both
11    MS          715        5.0            both
12    MT          907        4.0            both
13    PA          975        1.0            both
14    PB          536        6.0            both
15    PE         1652        9.0            both
16    PI          495        1.0            both
17    PR         5045      349.0            both
18    RJ        12852      171.0            both
19    RN          485        5.0            both
20    RO          253        2.0            both
21    RR           46        NaN  customers_only
22    RS         5466      129.0            both
23    SC         3637      190.0            both
24    SE          350        2.0            both
25    SP        41746     1849.0            both
26    TO          280        NaN  customers_only

Interpretation: based on the actual results, the states are distributed as follows: 23 present in both sets, 4 only among customers, 0 only among sellers.

,seller_a,seller_b,seller_state,city_a,city_b
0,1444c08e64d55fb3c25f0f09c07ffcf2,2b402d5dc42554061f8ea98d1916f148,BA,lauro de freitas,irece
1,1444c08e64d55fb3c25f0f09c07ffcf2,398cb257329ef7af7f1943a8974a3cbc,BA,lauro de freitas,salvador
2,1444c08e64d55fb3c25f0f09c07ffcf2,4221a7df464f1fe2955934e30ff3a5a1,BA,lauro de freitas,bahia
3,1444c08e64d55fb3c25f0f09c07ffcf2,43753b27d77860f1654aa72e251a7878,BA,lauro de freitas,barro alto
4,1444c08e64d55fb3c25f0f09c07ffcf2,4aba391bc3b88717ce08eb11e44937b2,BA,lauro de freitas,arraial d'ajuda (porto seguro)
5,1444c08e64d55fb3c25f0f09c07ffcf2,4fb41dff7c50136976d1a5cf004a42e2,BA,lauro de freitas,feira de santana
6,1444c08e64d55fb3c25f0f09c07ffcf2,651530bf5c607240ccdd89a30c9c9712,BA,lauro de freitas,ipira
7,1444c08e64d55fb3c25f0f09c07ffcf2,659e8466eb3ff1b0e8740d74fb7bbedd,BA,lauro de freitas,eunapolis
8,1444c08e64d55fb3c25f0f09c07ffcf2,75d34ebb1bd0bd7dde40dd507b8169c3,BA,lauro de freitas,salvador
9,1444c08e64d55fb3c25f0f09c07ffcf2,a3dd39f583bc80bd8c5901c95878921e,BA,lauro de freitas,salvador
10,1444c08e64d55fb3c25f0f09c07ffcf2,b00af24704019bd2e1b335e70ad11f7c,BA,lauro de freitas,salvador
11,1444c08e64d55fb3c25f0f09c07ffcf2,c72de06d72748d1a0dfb2125be43ba63,BA,lauro de freitas,guanambi
12,1444c08e64d55fb3c25f0f09c07ffcf2,d03698c2efd04a549382afa6623e27fb,BA,lauro de freitas,ilheus
13,1444c08e64d55fb3c25f0f09c07ffcf2,d2e753bb80b7d4faa77483ed00edc8ca,BA,lauro de freitas,porto seguro
14,1444c08e64d55fb3c25f0f09c07ffcf2,eb4a59a06b3948e851a7d7a830bcbc42,BA,lauro de freitas,salvador
15,1444c08e64d55fb3c25f0f09c07ffcf2,f3055483058c84d75ca2a3314fb4deef,BA,lauro de freitas,salvador
16,1444c08e64d55fb3c25f0f09c07ffcf2,fc59392d66ef99377e50356ee4f3b4e1,BA,lauro de freitas,salvador
17,2b402d5dc42554061f8ea98d1916f148,398cb257329ef7af7f1943a8974a3cbc,BA,irece,salvador
18,2b402d5dc42554061f8ea98d1916f148,4221a7df464f1fe2955934e30ff3a5a1,BA,irece,bahia
19,2b402d5dc42554061f8ea98d1916f148,43753b27d77860f1654aa72e251a7878,BA,irece,barro alto

Interpretation: the query found at least 20 pair(s) on the first page of results; for example, 1444c08e64d55fb3c25f0f09c07ffcf2 (lauro de freitas) and 2b402d5dc42554061f8ea98d1916f148 (irece) operate in the state of BA, but list different cities.
These are just the first 20 pairs. `IS DISTINCT FROM` also considers `NULL` to be distinct from a non-empty city, so rows with a missing city should be checked separately.

,order_id,customer_id,order_status,order_purchase_timestamp,total_without_review
0,cda873529ca7ab71f677d5ec11a40304,76c74aaff2f3f7355f46d9818ad092b8,shipped,2016-10-05 16:57:30,768
1,5da2004d85f2828349d887c989da2adc,95f592086150f0c95d3082aea047b816,delivered,2016-10-05 20:20:59,768
2,02190241f7190a1f3c7e0df95a749c6a,55c9044401ffab0c717f24405e2e042f,delivered,2016-10-07 10:52:22,768
3,0efd0bc268d34da3f01f4ff25a6d4335,95446917717bb58d553d107d0f1668f6,shipped,2016-10-07 15:53:31,768
4,c776863a93dc0740c6e7d78104b21413,1710b798ebdc5db6665c815b90a64999,delivered,2016-10-10 15:01:27,768
5,d730d8d0ea3149120703933fdf98b2d4,ce2a66464da8b80dedd7639a6e489a58,shipped,2017-01-13 20:12:41,768
6,05cd156f0f47579a36d7a52724fc31b8,976224a95faf328b17654b1b1411d5e1,delivered,2017-01-14 18:27:28,768
7,719b940ab2f1e351ffb14a0a02ffe3c4,ede9a1daf58d256c0d648ef7e1479010,delivered,2017-01-16 13:01:51,768
8,fbd82b1fe98967de0db29b6cf134d00a,45f5c9d984dbfa2105e3544cc85133bf,delivered,2017-01-18 08:55:36,768
9,171398a0cd843c65ac78aee9e05a1f49,f0244902c07b7c0799e468218579a925,delivered,2017-01-18 16:07:37,768
10,fcda3cc8210e746326864eb933641ccf,fee7cf49127308e2b5402c9984b6f1f6,delivered,2017-01-18 22:41:55,768
11,58a4317c14bcba43d0cf161f17e9db2b,e7f5b701d99a5eb91e57a970a75640f0,delivered,2017-01-30 11:55:23,768
12,ee55010a370e987f203499f435a59847,9f074c63790b0ef8b01c66fd67a97601,delivered,2017-01-30 15:17:47,768
13,91bcbd0102f5188ea47df5bcc83f3cad,0e63522224dc7d760139532f17a3634f,delivered,2017-01-31 02:29:51,768
14,5f6b520cff06f23c77386b75976256e9,38e08b021ffa6f71de788a0e30c9c65a,delivered,2017-01-31 11:58:52,768
15,ecfc862cb2fabd3d5f9c86117a9baff0,5bb03a9d99d476e8634520ceb63e08d6,delivered,2017-02-05 19:13:56,768
16,5f2dbe00a1732133a6809ae1af554123,f7b1d4b064c31b564fd39ad8bcb7cbdc,unavailable,2017-02-06 08:18:30,768
17,0c4d07bcd65a6ce95cbe8e8e228a98cf,30d6a066b7e76c8fd66610d4b36e891d,delivered,2017-02-06 12:15:34,768
18,6c895a26a7b113a890c888e46f106907,55eaa25f13d0d25081e707fc622c64b1,delivered,2017-02-09 11:38:52,768
19,765388e7b3d416ffe810ade706854872,a7288cab9fc524abf65915630e66c73b,delivered,2017-02-09 13:52:13,768

Interpretation: there are 768 orders with no reviews; the first 20, ordered by creation time, are shown above.

,product_category_name,n_orders,gross_revenue,freight,avg_item_price
0,beleza_saude,8836,1258681.34,182566.73,130.16
1,relogios_presentes,5624,1205005.68,100535.93,201.14
2,cama_mesa_banho,9417,1036988.68,204693.04,93.30
3,esporte_lazer,7720,988048.97,168607.51,114.34
4,informatica_acessorios,6689,911954.32,147318.08,116.51
5,moveis_decoracao,6449,729762.49,172749.30,87.56
6,cool_stuff,3632,635290.85,84039.10,167.36
7,utilidades_domesticas,5884,632248.66,146149.11,90.79
8,automotivo,3897,592720.11,92664.21,139.96
9,ferramentas_jardim,3518,485256.46,98962.75,111.63
10,brinquedos,3886,483946.60,77425.95,117.55
11,bebes,2885,411764.89,68353.11,134.34
12,perfumaria,3162,399124.87,54213.84,116.74
13,telefonia,4199,323667.53,71215.79,71.21
14,moveis_escritorio,1273,273960.70,68571.95,162.01
15,papelaria,2311,230943.23,46798.48,91.75
16,pcs,181,222963.13,9836.30,1098.34
17,pet_shop,1710,214315.41,39561.24,110.07
18,instrumentos_musicais,628,191498.88,18638.49,281.62
19,eletroportateis,630,190648.58,16020.25,280.78
20,None,1451,179535.28,28169.81,112.00
21,eletronicos,2550,160246.74,46578.32,57.91
22,consoles_games,1062,157465.22,19828.02,138.49
23,fashion_bolsas_e_acessorios,1864,152823.54,31450.00,75.25
24,construcao_ferramentas_construcao,748,144677.59,20650.41,155.73
25,malas_acessorios,1034,140429.98,30445.23,128.60
26,eletrodomesticos_2,234,113317.74,10600.18,476.12
27,casa_construcao,490,83088.12,13832.24,137.56
28,eletrodomesticos,764,80171.53,14818.90,103.98
29,agro_industria_e_comercio,182,72530.47,5843.60,342.12
30,moveis_sala,422,68916.56,17968.17,137.01
31,telefonia_fixa,217,59583.00,4637.81,225.69
32,casa_conforto,397,58572.04,8501.23,134.96
33,climatizacao,253,55024.96,6749.23,185.27
34,audio,350,50688.50,5710.44,139.25
35,portateis_casa_forno_e_cafe,75,47445.71,2747.86,624.29
36,livros_interesse_geral,512,46856.88,9195.52,84.73
37,moveis_cozinha_area_de_servico_jantar_e_jardim,248,46328.37,11999.43,164.87
38,construcao_ferramentas_iluminacao,244,41080.00,7583.80,135.13
39,construcao_ferramentas_seguranca,167,40544.52,3919.10,208.99
40,industria_comercio_e_negocios,235,39669.61,7884.68,148.02
41,alimentos,450,29393.41,7271.03,57.63
42,market_place,280,28378.47,5456.06,91.25
43,construcao_ferramentas_jardim,194,25715.89,5311.40,108.05
44,artes,202,24202.64,4045.17,115.80
45,fashion_calcados,240,23562.77,4918.87,89.93
46,bebidas,297,22428.70,5741.25,59.18
47,sinalizacao_e_seguranca,140,21509.23,6507.82,108.09
48,moveis_quarto,95,20028.78,4632.23,183.75
49,livros_tecnicos,260,19096.06,4283.06,71.52
50,construcao_ferramentas_ferramentas,97,15903.95,2030.22,154.41
51,alimentos_bebidas,227,15179.48,4507.99,54.60
52,fashion_roupa_masculina,112,10797.82,2152.41,81.80

Interpretation: Among the categories that passed the HAVING threshold, the highest gross revenue is in the category beleza_saude: 1,258,681.34; 8836 orders, with an average item price of 130.16.

   customer_state  n_orders         gmv     aov
0              PB       532   140987.81  265.01
1              AL       411    96229.40  234.13
2              RO       247    57558.02  233.03
3              PA       970   217647.11  224.38
4              TO       279    61354.42  219.91
5              PI       493   108132.28  219.34
6              SE       345    73032.32  211.69
7              RN       482   101895.08  211.40
8              CE      1327   275606.30  207.69
9              MT       903   186168.96  206.17
10             MA       740   151171.99  204.29
11             PE      1648   322237.69  195.53
12             MS       709   135956.67  191.76
13             AM       147    27835.73  189.36
14             BA      3358   611506.67  182.10
15             GO      2007   347706.93  173.25
16             SC      3612   610213.60  168.94
17             RJ     12762  2129681.98  166.88
18             DF      2125   353229.44  166.23
19             RS      5432   885826.76  163.08
20             MG     11544  1856161.49  160.79
21             ES      2025   324801.91  160.40
22             PR      4998   800935.44  160.25
23             SP     41375  5921678.12  143.12

Interpretation: Among states with at least 100 orders, the highest AOV is in PB: 265.01 per order (532 orders, GMV 140,987.81).

,customer_unique_id,n_orders,total_spend,categories
0,0a0a92112bd4c708ca5fde585afaa872,1,13440.00,telefonia_fixa
1,da122df9eeddfedc1dc1f5349a1a690c,2,7388.00,eletroportateis
2,763c8b1c9c68a0229c42c9fc6f662b93,1,7160.00,telefonia_fixa
3,dc4802a71eae9be1dd28f5d788ceb526,1,6735.00,utilidades_domesticas
4,459bef486812aa25204be022145caa62,1,6729.00,pcs
5,ff4159b92c40ebe40454e3e6a7c35ed6,1,6499.00,artes
6,4007669dec559734d6f53e029e360987,1,5934.60,agro_industria_e_comercio
7,eebb5dda148d3893cdaf5b5ca3040ccb,1,4690.00,eletroportateis
8,5d0a2980b292d049061542014e8960bf,1,4599.90,cool_stuff
9,48e1ac109decbb87765a3eade6854098,1,4590.00,pcs
10,a229eba70ec1c2abef51f04987deb7a5,1,4400.00,relogios_presentes
11,edde2314c6c30e864a128ac95d6b2112,1,4399.87,instrumentos_musicais
12,fa562ef24d41361e476e748681810e1e,1,4099.99,consoles_games
13,c8460e4251689ba205045f3ea17884a1,4,4080.00,telefonia
14,ca27f3dac28fb1063faddd424c9d95fa,1,4059.00,esporte_lazer
15,055ec572ac7f3c7bdd04a183830ebe59,2,3999.98,automotivo
16,011875f0176909c5cf0b14a9138bb691,1,3999.90,relogios_presentes
17,edf81e1f3070b9dac83ec83dacdbb9bc,1,3999.00,eletroportateis
18,5e713be0853d8986528d7869a0811d2b,1,3980.00,(unknown)
19,f0767ae738c3d90e7b737d7b8b8bb4d1,1,3930.00,ferramentas_jardim

ІInterpretation: Among the customers shown, 0a0a92112bd4c708ca5fde585afaa872 has the highest spending: 13,440.00 across 1 orders. Categories involved: telefonia_fixa.

   state      role
0     AC  customer
1     AC    seller
2     AL  customer
3     AM  customer
4     AM    seller
5     AP  customer
6     BA  customer
7     BA    seller
8     CE  customer
9     CE    seller
10    DF  customer
11    DF    seller
12    ES  customer
13    ES    seller
14    GO  customer
15    GO    seller
16    MA  customer
17    MA    seller
18    MG  customer
19    MG    seller
20    MS  customer
21    MS    seller
22    MT  customer
23    MT    seller
24    PA  customer
25    PA    seller
26    PB  customer
27    PB    seller
28    PE  customer
29    PE    seller
30    PI  customer
31    PI    seller
32    PR  customer
33    PR    seller
34    RJ  customer
35    RJ    seller
36    RN  customer
37    RN    seller
38    RO  customer
39    RO    seller
40    RR  customer
41    RS  customer
42    RS    seller
43    SC  customer
44    SC    seller
45    SE  customer
46    SE    seller
47    SP  customer
48    SP    seller
49    TO  customer

Interpretation: There are 27 unique state codes in the datasets; 23 of these are represented among both clients and sellers. UNION retained the unique state-role pairs.

,customer_unique_id,customer_id,order_id,order_purchase_timestamp
0,0000366f3b9a7992bf8c76cfdf3221e2,fadbb3709178fc513abc1b2670aa1ad2,e22acc9c116caa3f2b7121bbb380d08e,2018-05-10 10:56:27
1,0000b849f77a49e4a4ce2b2a4ca5be3f,4cb282e167ae9234755102258dd52ee8,3594e05a005ac4d06a72673270ef9ec9,2018-05-07 11:11:27
2,0000f46a3911fa3c0805444483337064,9b3932a6253894a02c1df9d19004239f,b33ec3b699337181488304f362a6b734,2017-03-10 21:05:03
3,0000f6ccb0745a6a4b88665a16c9f078,914991f0c02ef0843c0e7010c819d642,41272756ecddd9a9ed0180413cc22fb6,2017-10-12 20:29:41
4,0004aac84e0df4da2b147fca70cf8255,47227568b10f5f58a524a75507e6992c,d957021f1127559cd947b62533f484f7,2017-11-14 19:45:42
5,0004bd2a26a76fe21f786e4fbd80607f,4a913a170c26e3c8052ed0202849b5a8,3e470077b690ea3e3d501cffb5e0c499,2018-04-05 19:33:16
6,00050ab1314c0e55a6ca13cf7181fecf,d2509c13692836fc0449e88cf9eb4858,d0028facea13f508e880202d7097a5a1,2018-04-20 12:57:23
7,00053a61a98854899e70ed204dd4bafe,a81ebb9b32f102298c0c89635b4b3154,44e608f2db00c74a1fe329de44416a4e,2018-02-28 11:15:41
8,0005e1862207bf6ccc02e4228effd9a0,3b37fb626fdf46cd99d37ec62afa88ff,ae76bef74b97bcb0b3e355e60d9a6f9c,2017-03-04 23:32:12
9,0005ef4cd20d2893f0d9fbd94d3c0d97,c59e8ff99836e90d8b457d4122dc34e9,01b330808c5819a6a3cb79b72f0b8288,2018-03-12 15:22:12
10,0006fdc98a402fceb4eb0ee528f6a8d4,2f29573c8cac5a7be11c5b649078f944,6681163e3dab91c549952b2845b20281,2017-07-18 09:23:10
11,00082cbe03e478190aadbea78542e933,9dec2d47e95677b616efe366f8bf9fb8,67503374d1fbcbe5e3a40324f703ffc8,2017-11-19 15:22:02
12,00090324bbad0e9342388303bb71ba0a,40f0183f7439212e8ce53dc6103dfb2f,85bf8863657bff31006811d45d1c8db9,2018-03-24 14:44:41
13,000949456b182f53c18b68d6babc79c1,64eb9409c29c87a0a90ee1e08ce05065,d342d7bad292d68d41d58ffb594cf431,2018-04-23 09:55:46
14,000a5ad9c4601d2bbdd9ed765d5213b3,be22f11baf346059cbe6556ef9c69070,f7fa5cf8386e51037856df1add3e1228,2017-08-11 13:45:15
15,000bfa1d2f1a41876493be685390d6d3,e36917a47d5bf39bd3f38bcafb3d438f,fd61441ba2a7b57e6342862e779b10b0,2017-09-29 14:46:58
16,000c8bdb58a29e7115cfc257230fb21b,0e114b02a45c9876080f3a9a19f51c16,34801c59d6ec5c5e89bfefb6ebef314d,2017-12-12 22:53:35
17,000d460961d6dbfa3ec6c9f5805769e1,4948d9d11ebcd4d241a0b291c15d5779,5fd641e5e16c3b056b1fb4dd6e429c43,2018-01-07 22:59:25
18,000de6019bb59f34c099a907c151d855,455f2e2988eaf87d7e2ba33b0a57969f,c6d61340bd8baeedca7cc8e7f7ec07e9,2017-08-17 19:10:33
19,000e309254ab1fc5ba99dd469d36bdb4,8866a052aebe7f7cee97bace65b379b2,c5d3fae065a8090bae39f4f34b14cd06,2018-06-25 09:53:57

Interpretation: 20 customers are shown, along with one most recent order for each of the first 20 customer_unique_id values.

Відповідь на завдання 2.

Навіщо потрібен RETURNING.

"INSERT ... RETURNING" одразу повертає поля щойно створеного "alert" — наприклад, його "alert_id", продавця, тип і час створення. Тому не потрібно запускати окремий "SELECT", щоб перевірити результат вставки. У notebook ці дані можна показати й зберегти в "alert_audit_log" для аудиту: буде видно, який "alert" створив запит і коли. Примітка: для довготривалого аудиту результат потрібно окремо зберегти; вивід клітинки сам по собі не є постійним сховищем.

Пояснення "seller_score".

"seller_orders" використовує "SELECT DISTINCT", щоб кожна пара "seller_id × order_id" враховувалася лише один раз. Якщо продавець має кілька позицій в одному замовленні, це не повинно збільшувати кількість його замовлень.

"Review" спочатку агрегується до рівня "order_id", бо відгук стосується замовлення, а не окремої позиції. Якщо приєднати його безпосередньо до "order_items", один відгук повториться для кожної позиції в замовленні й спотворить середню оцінку.

"ON CONFLICT (seller_id) DO UPDATE" використовує "seller_id" як ключ: коли рядок для продавця вже існує, запит оновлює його метрики замість вставки дубліката. Тому повторний запуск перераховує ті самі рядки.

Для продавця без ненульових оцінок AVG повертає "NULL", а "COUNT" — 0. Оскільки рейтинг не обчислено, "tier" теж залишається "NULL".

Відповідь на завдання 3.

"customer_segments" використовує "customer_unique_id", бо він ідентифікує реального покупця між різними замовленнями. "customer_id" може бути різним для повторних покупок, тож сегментація за ним розділила б історію клієнта.

"olist_customer_dim" містить один рядок на "customer_unique_id". Це дає змогу посилатися на покупця зовнішнім ключем і гарантувати цілісність зв’язку.

"reference_date" з датасету робить обчислення "recency" стабільним для історичних даних. "CURRENT_DATE" змінив би сегменти залежно від дня запуску notebook.

"ON CONFLICT (customer_unique_id) DO UPDATE" оновлює наявний сегмент покупця замість створення дубліката, тому запит можна запускати повторно.

Відповідь на завдання 5.

"review_per_order" агрегує оцінки на рівні замовлення до приєднання до покупця. Це захищає оцінку від множення через позиції замовлення.

WHERE і HAVING.
"WHERE" фільтрує окремі рядки до групування й обчислення агрегатів. Наприклад, у запиті "RPPC" можна додати "WHERE oi.price > 0", щоб прибрати безкоштовні позиції перед розрахунком виторгу категорії.
"HAVING" фільтрує вже сформовані групи після агрегації. У "RPPC" умова "HAVING SUM(oi.price) > 10000" залишає лише категорії, сукупний виторг яких перевищує поріг. У "number_of_orders" "HAVING COUNT(*) >= 100" залишає лише штати з достатньою кількістю замовлень.

Reflection.

У JOIN-запитах найскладнішим для мене було контролювати гранулярність: відгук належить замовленню, а позиції — продавцям і товарам. Просте з'єднання відгуків із позиціями повторює оцінку, тому перед "seller-score" я агрегував відгуки на рівні "order_id", а товари — на рівні "seller_id × order_id". Найважче було перетворити це на бізнес-питання про рейтинг продавця: треба пояснити, що оцінка спільного замовлення може бути приписана кільком продавцям.
Для production-ETL найкориснішим вважаю "ON CONFLICT": він дає змогу регулярно перераховувати метрики без дублікатів. "Constraints" доповнюють його, зупиняючи некоректні значення, а "RETURNING" допомагає записувати змінені рядки в аудит. "Window functions" я застосував би для останнього замовлення покупця, ранжування продавців у категоріях, ковзних витрат і побудови часових ознак для "train/test split" без витоку майбутнього.
У "Olist" є замовлення без "review", пропущені назви категорій, а коментарі відгуків можуть бути порожніми. Статуси "canceled" та "unavailable" треба трактувати як окремі бізнес-стани, а не автоматично вважати помилкою. Перед моделлю я перевірив би дублікати "review" та пропуски метрик кількісно. Для "customer-level" ознак використовую "customer_unique_id": "customer_id" розділяє доставки/замовлення одного покупця, а "unique ID" дає змогу коректно порахувати "frequency" та історію. Для seller-score потрібна гранулярність "seller_id × order_id", щоб багато позицій одного продавця в замовленні не збільшували кількість голосів.